/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examenlab5p2_heydenalfonsoaldanavarela;

import javax.swing.JOptionPane;

/**
 *
 * @author heyde
 */
public class jfrmAdmin extends javax.swing.JFrame {

     private g_admin a;
    /**
     * Creates new form jfrmAdmin
     */
    public jfrmAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        tnombre1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tusuario2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tsaldo = new javax.swing.JTextField();
        tedad1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tcuentabancaria1 = new javax.swing.JTextField();
        jrbadmin1 = new javax.swing.JRadioButton();
        jrbcompra1 = new javax.swing.JRadioButton();
        jrbventa1 = new javax.swing.JRadioButton();
        beditar = new javax.swing.JButton();
        tpersonajefav1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tcontra2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tsaldoc = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tusuario1 = new javax.swing.JTextField();
        beliminar = new javax.swing.JButton();
        jrbadmin2 = new javax.swing.JRadioButton();
        jrbcompra2 = new javax.swing.JRadioButton();
        jrbventa2 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tnombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tusuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tcontra = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tedad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tcuentabancaria = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tpersonajefav = new javax.swing.JTextField();
        jrbadmin = new javax.swing.JRadioButton();
        jrbcompra = new javax.swing.JRadioButton();
        jrbventa = new javax.swing.JRadioButton();
        bcrear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tadmin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 51, 0));

        jTabbedPane1.setBackground(new java.awt.Color(102, 102, 0));
        jTabbedPane1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(102, 102, 0));

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setText("Nombre Real");

        tnombre1.setBackground(new java.awt.Color(255, 255, 153));
        tnombre1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setText("Usuario a Modificar");

        tusuario2.setBackground(new java.awt.Color(255, 255, 153));
        tusuario2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel11.setText("Contraseña");

        tsaldo.setBackground(new java.awt.Color(255, 255, 153));
        tsaldo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        tedad1.setBackground(new java.awt.Color(255, 255, 153));
        tedad1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel12.setText("Edad");

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel13.setText("Cuenta Bancaria (7 digitos)");

        tcuentabancaria1.setBackground(new java.awt.Color(255, 255, 153));
        tcuentabancaria1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jrbadmin1.setBackground(new java.awt.Color(102, 102, 0));
        jrbadmin1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jrbadmin1.setText("Administrador");
        jrbadmin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbadmin1ActionPerformed(evt);
            }
        });

        jrbcompra1.setBackground(new java.awt.Color(102, 102, 0));
        jrbcompra1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jrbcompra1.setText("Comprador");
        jrbcompra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbcompra1ActionPerformed(evt);
            }
        });

        jrbventa1.setBackground(new java.awt.Color(102, 102, 0));
        jrbventa1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jrbventa1.setText("Vendedor");
        jrbventa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbventa1ActionPerformed(evt);
            }
        });

        beditar.setBackground(new java.awt.Color(102, 153, 0));
        beditar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        beditar.setText("Editar usuario");
        beditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beditarActionPerformed(evt);
            }
        });

        tpersonajefav1.setBackground(new java.awt.Color(255, 255, 153));
        tpersonajefav1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel14.setText("Personaje favorito");

        tcontra2.setBackground(new java.awt.Color(255, 255, 153));
        tcontra2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel15.setText("Saldo");

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel16.setText("Saldo compra");

        tsaldoc.setBackground(new java.awt.Color(255, 255, 153));
        tsaldoc.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(58, 58, 58)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tedad1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(tcuentabancaria1)))
                    .addComponent(tnombre1)
                    .addComponent(tusuario2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(beditar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbventa1)
                            .addComponent(jrbcompra1)
                            .addComponent(jrbadmin1)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tpersonajefav1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(tsaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(tsaldoc, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(tcontra2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(252, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tnombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(tusuario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tedad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tcuentabancaria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tpersonajefav1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tsaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tsaldoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jrbadmin1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrbcompra1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrbventa1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(beditar, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(194, 194, 194)
                    .addComponent(tcontra2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(226, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Editar Usuarios", jPanel3);

        jPanel4.setBackground(new java.awt.Color(102, 102, 0));

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setText("Nombre de Usuario");

        tusuario1.setBackground(new java.awt.Color(255, 255, 153));
        tusuario1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        beliminar.setBackground(new java.awt.Color(102, 153, 0));
        beliminar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        beliminar.setText("Eliminar usuario");
        beliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beliminarActionPerformed(evt);
            }
        });

        jrbadmin2.setBackground(new java.awt.Color(102, 102, 0));
        jrbadmin2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jrbadmin2.setText("Administrador");
        jrbadmin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbadmin2ActionPerformed(evt);
            }
        });

        jrbcompra2.setBackground(new java.awt.Color(102, 102, 0));
        jrbcompra2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jrbcompra2.setText("Comprador");
        jrbcompra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbcompra2ActionPerformed(evt);
            }
        });

        jrbventa2.setBackground(new java.awt.Color(102, 102, 0));
        jrbventa2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jrbventa2.setText("Vendedor");
        jrbventa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbventa2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(191, 191, 191))
                            .addComponent(tusuario1, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jrbventa2)
                                    .addComponent(jrbcompra2)
                                    .addComponent(jrbadmin2))
                                .addGap(132, 132, 132))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(beliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(110, 110, 110))))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tusuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jrbadmin2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbcompra2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbventa2)
                .addGap(18, 18, 18)
                .addComponent(beliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addGap(116, 116, 116))
        );

        jTabbedPane1.addTab("Eliminar Usuarios", jPanel4);

        jPanel2.setBackground(new java.awt.Color(102, 102, 0));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Nombre Real");

        tnombre.setBackground(new java.awt.Color(255, 255, 153));
        tnombre.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Nombre de Usuario");

        tusuario.setBackground(new java.awt.Color(255, 255, 153));
        tusuario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("Contraseña");

        tcontra.setBackground(new java.awt.Color(255, 255, 153));
        tcontra.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("Edad");

        tedad.setBackground(new java.awt.Color(255, 255, 153));
        tedad.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setText("Cuenta Bancaria (7 digitos)");

        tcuentabancaria.setBackground(new java.awt.Color(255, 255, 153));
        tcuentabancaria.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setText("Personaje favorito");

        tpersonajefav.setBackground(new java.awt.Color(255, 255, 153));
        tpersonajefav.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jrbadmin.setBackground(new java.awt.Color(102, 102, 0));
        jrbadmin.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jrbadmin.setText("Administrador");
        jrbadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbadminActionPerformed(evt);
            }
        });

        jrbcompra.setBackground(new java.awt.Color(102, 102, 0));
        jrbcompra.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jrbcompra.setText("Comprador");
        jrbcompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbcompraActionPerformed(evt);
            }
        });

        jrbventa.setBackground(new java.awt.Color(102, 102, 0));
        jrbventa.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jrbventa.setText("Vendedor");
        jrbventa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbventaActionPerformed(evt);
            }
        });

        bcrear.setBackground(new java.awt.Color(102, 153, 0));
        bcrear.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        bcrear.setText("Crear usuario");
        bcrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(tcontra, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tedad, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(tcuentabancaria)))
                    .addComponent(tnombre)
                    .addComponent(tusuario)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jrbadmin))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(tpersonajefav, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bcrear, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jrbventa)
                                    .addComponent(jrbcompra))))
                        .addGap(16, 16, 16)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tcontra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tcuentabancaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jrbadmin)
                        .addGap(18, 18, 18)
                        .addComponent(jrbcompra))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tpersonajefav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jrbventa)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(bcrear, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Crear Usuarios", jPanel2);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Administrador:");

        tadmin.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tadmin.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(tadmin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tadmin))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbadminActionPerformed
        // TODO add your handling code here:
        jrbcompra.setSelected(false);
        jrbventa.setSelected(false);
    }//GEN-LAST:event_jrbadminActionPerformed

    private void jrbcompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbcompraActionPerformed
        // TODO add your handling code here:
        jrbadmin.setSelected(false);
        jrbventa.setSelected(false);
    }//GEN-LAST:event_jrbcompraActionPerformed

    private void jrbventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbventaActionPerformed
        // TODO add your handling code here:
        jrbadmin.setSelected(false);
        jrbcompra.setSelected(false);
    }//GEN-LAST:event_jrbventaActionPerformed

    private void bcrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcrearActionPerformed
        // TODO add your handling code here:

        try
        {
            int edad = Integer.parseInt(tedad.getText());
            if(tcuentabancaria.getText().length() != 7)
            {
                JOptionPane.showMessageDialog(null, "ADVERTENCIA: La cuenta bancaria debe ser de 7 digitos");
                return;
            }

            // agrega segun sol
            if(jrbadmin.isSelected())
                a.crearUsuarioAdmin(tnombre.getText(), tusuario.getText(), tcontra.getText(), edad);
            else if(jrbcompra.isSelected())
                a.crearUsuarioCompra(tnombre.getText(), tusuario.getText(), tcontra.getText(), edad, tcuentabancaria.getText());
            else if(jrbventa.isSelected())
                a.crearUsuarioVenta(tnombre.getText(), tusuario.getText(), tcontra.getText(), edad, tcuentabancaria.getText(), tpersonajefav.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR DEL SISTEMA: no se puede agregar los datos\n" + "¿Escribio los datos correctamente?");
        }

    }//GEN-LAST:event_bcrearActionPerformed

    private void beliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beliminarActionPerformed
        try
        {
            if(jrbadmin.isSelected())
                a.eliminarUsuario("administrador", tusuario.getText());
            else if(jrbcompra.isSelected())
                a.eliminarUsuario("comprador", tusuario.getText());
             else if(jrbventa.isSelected())
                a.eliminarUsuario("vendedor", tusuario.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR DEL SISTEMA");
        }
    }//GEN-LAST:event_beliminarActionPerformed

    private void jrbadmin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbadmin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbadmin1ActionPerformed

    private void jrbcompra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbcompra1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbcompra1ActionPerformed

    private void jrbventa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbventa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbventa1ActionPerformed

    private void beditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beditarActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        try
        {
            int edad = Integer.parseInt(tedad.getText());
            double saldo = Double.parseDouble(tsaldo.getText());
            double saldocompra = Double.parseDouble(tsaldoc.getText());
            if(tcuentabancaria.getText().length() != 7)
            {
                JOptionPane.showMessageDialog(null, "ADVERTENCIA: La cuenta bancaria debe ser de 7 digitos");
                return;
            }

            // agrega segun sol
            
            if(jrbadmin.isSelected())
                a.crearUsuarioAdmin(tnombre.getText(), tusuario.getText(), tcontra.getText(), edad);
            else if(jrbcompra.isSelected())
                a.editarUsuarioComprador(tnombre.getText(), tusuario.getText(), tcontra.getText(), edad, tcuentabancaria.getText(), saldo, saldocompra);
            else if(jrbventa.isSelected())
                a.editarUsuarioVendedor(tnombre.getText(), tusuario.getText(), tcontra.getText(), edad, tcuentabancaria.getText(), saldo, tpersonajefav.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR DE ESCRITURA DEL SISTEMA");
        }
    }//GEN-LAST:event_beditarActionPerformed

    private void jrbadmin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbadmin2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbadmin2ActionPerformed

    private void jrbcompra2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbcompra2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbcompra2ActionPerformed

    private void jrbventa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbventa2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbventa2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcrear;
    private javax.swing.JButton beditar;
    private javax.swing.JButton beliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton jrbadmin;
    private javax.swing.JRadioButton jrbadmin1;
    private javax.swing.JRadioButton jrbadmin2;
    private javax.swing.JRadioButton jrbcompra;
    private javax.swing.JRadioButton jrbcompra1;
    private javax.swing.JRadioButton jrbcompra2;
    private javax.swing.JRadioButton jrbventa;
    private javax.swing.JRadioButton jrbventa1;
    private javax.swing.JRadioButton jrbventa2;
    private javax.swing.JLabel tadmin;
    private javax.swing.JTextField tcontra;
    private javax.swing.JTextField tcontra2;
    private javax.swing.JTextField tcuentabancaria;
    private javax.swing.JTextField tcuentabancaria1;
    private javax.swing.JTextField tedad;
    private javax.swing.JTextField tedad1;
    private javax.swing.JTextField tnombre;
    private javax.swing.JTextField tnombre1;
    private javax.swing.JTextField tpersonajefav;
    private javax.swing.JTextField tpersonajefav1;
    private javax.swing.JTextField tsaldo;
    private javax.swing.JTextField tsaldoc;
    private javax.swing.JTextField tusuario;
    private javax.swing.JTextField tusuario1;
    private javax.swing.JTextField tusuario2;
    // End of variables declaration//GEN-END:variables
}
